spring:
  profiles:
    active: h2_persist
  datasource:
    username: ${BD_USERNAME}
    password: ${BD_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO

telegram:
  bot-token: ${TG_TOKEN}
  long-polling-timeout: 60

open-ai:
  token: ${OPENAI_TOKEN}
  base-url: https://api.openai.com
  completion-model: gpt-3.5-turbo
  chat-completion-model: gpt-3.5-turbo