spring:
  profiles:
    active: default

logging:
  level:
    root: INFO

telegram:
  bot-token: ${TG_TOKEN}
  base-url: https://api.telegram.org
  long-polling-timeout: 60

open-ai:
  token: ${OPENAI_TOKEN}
  base-url: https://api.openai.com

game:
  game-question-cont: 3