name: Test&Build&Push

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant permission to gradlew
        run: chmod +x gradlew

      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Build application
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootJar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: build/libs/app.jar

  push-to-DockerHub:
    needs: build

    if: ${{ github.ref_name == 'main' }}

    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app.jar
          path: build/libs

      - name: Build image and push to DockerHub
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/telegram-bot
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
