name: Test&Build&Push

on: push

env:
  TAG_WITHOUT_VERSION: ${{ secrets.DOCKERHUB_USERNAME }}/telegram-bot

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant permission to gradlew
        run: chmod +x gradlew

      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Build application
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootJar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app.jar
          path: build/libs/app.jar


  extract-commit-sha:
    runs-on: ubuntu-latest

    steps:
      # take first 4 symbols from github.sha
      - run: echo "COMMIT_SHA=${{ github.sha }}" | cut -c1-15 >> $GITHUB_ENV


  push-to-DockerHub:
    needs: build

    #    if: ${{ github.ref_name == 'main' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app.jar
          path: build/libs

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (main-sha)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.TAG_WITHOUT_VERSION }}:${{ github.ref_name.replace('/', '-') }}-${{ env.COMMIT_SHA }}

      - name: Build and push (latest)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.TAG_WITHOUT_VERSION }}:${{ env.LATEST_TAG }}
